<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="MedievalRussia">
			<HintPath>..\libs\MedievalRussia.dll</HintPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Reference>
	</ItemGroup>

</Project>